/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package DataBase.model.impl;

import DataBase.model.Bank;
import DataBase.model.BankModel;
import DataBase.model.BankSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Bank service. Represents a row in the &quot;My_Bank&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BankModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BankImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BankImpl
 * @generated
 */
@JSON(strict = true)
public class BankModelImpl extends BaseModelImpl<Bank> implements BankModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bank model instance should use the <code>Bank</code> interface instead.
	 */
	public static final String TABLE_NAME = "My_Bank";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"Bank_id", Types.BIGINT},
		{"BankName", Types.VARCHAR}, {"Bic", Types.BIGINT},
		{"Address", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Bank_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("BankName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Bic", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("Address", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table My_Bank (uuid_ VARCHAR(75) null,Bank_id LONG not null primary key,BankName VARCHAR(75) null,Bic LONG,Address VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table My_Bank";

	public static final String ORDER_BY_JPQL = " ORDER BY bank.Bank_id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY My_Bank.Bank_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long BANKNAME_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long BANK_ID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Bank toModel(BankSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Bank model = new BankImpl();

		model.setUuid(soapModel.getUuid());
		model.setBank_id(soapModel.getBank_id());
		model.setBankName(soapModel.getBankName());
		model.setBic(soapModel.getBic());
		model.setAddress(soapModel.getAddress());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Bank> toModels(BankSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Bank> models = new ArrayList<Bank>(soapModels.length);

		for (BankSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public BankModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Bank_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBank_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Bank_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Bank.class;
	}

	@Override
	public String getModelClassName() {
		return Bank.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Bank, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Bank, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Bank, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Bank)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Bank, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Bank, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Bank)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Bank, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Bank, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Bank>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Bank.class.getClassLoader(), Bank.class, ModelWrapper.class);

		try {
			Constructor<Bank> constructor =
				(Constructor<Bank>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Bank, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Bank, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Bank, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Bank, Object>>();
		Map<String, BiConsumer<Bank, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Bank, ?>>();

		attributeGetterFunctions.put("uuid", Bank::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Bank, String>)Bank::setUuid);
		attributeGetterFunctions.put("Bank_id", Bank::getBank_id);
		attributeSetterBiConsumers.put(
			"Bank_id", (BiConsumer<Bank, Long>)Bank::setBank_id);
		attributeGetterFunctions.put("BankName", Bank::getBankName);
		attributeSetterBiConsumers.put(
			"BankName", (BiConsumer<Bank, String>)Bank::setBankName);
		attributeGetterFunctions.put("Bic", Bank::getBic);
		attributeSetterBiConsumers.put(
			"Bic", (BiConsumer<Bank, Long>)Bank::setBic);
		attributeGetterFunctions.put("Address", Bank::getAddress);
		attributeSetterBiConsumers.put(
			"Address", (BiConsumer<Bank, String>)Bank::setAddress);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getBank_id() {
		return _Bank_id;
	}

	@Override
	public void setBank_id(long Bank_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Bank_id = Bank_id;
	}

	@JSON
	@Override
	public String getBankName() {
		if (_BankName == null) {
			return "";
		}
		else {
			return _BankName;
		}
	}

	@Override
	public void setBankName(String BankName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_BankName = BankName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalBankName() {
		return getColumnOriginalValue("BankName");
	}

	@JSON
	@Override
	public long getBic() {
		return _Bic;
	}

	@Override
	public void setBic(long Bic) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Bic = Bic;
	}

	@JSON
	@Override
	public String getAddress() {
		if (_Address == null) {
			return "";
		}
		else {
			return _Address;
		}
	}

	@Override
	public void setAddress(String Address) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Address = Address;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Bank.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Bank toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Bank>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BankImpl bankImpl = new BankImpl();

		bankImpl.setUuid(getUuid());
		bankImpl.setBank_id(getBank_id());
		bankImpl.setBankName(getBankName());
		bankImpl.setBic(getBic());
		bankImpl.setAddress(getAddress());

		bankImpl.resetOriginalValues();

		return bankImpl;
	}

	@Override
	public int compareTo(Bank bank) {
		int value = 0;

		if (getBank_id() < bank.getBank_id()) {
			value = -1;
		}
		else if (getBank_id() > bank.getBank_id()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Bank)) {
			return false;
		}

		Bank bank = (Bank)object;

		long primaryKey = bank.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Bank> toCacheModel() {
		BankCacheModel bankCacheModel = new BankCacheModel();

		bankCacheModel.uuid = getUuid();

		String uuid = bankCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			bankCacheModel.uuid = null;
		}

		bankCacheModel.Bank_id = getBank_id();

		bankCacheModel.BankName = getBankName();

		String BankName = bankCacheModel.BankName;

		if ((BankName != null) && (BankName.length() == 0)) {
			bankCacheModel.BankName = null;
		}

		bankCacheModel.Bic = getBic();

		bankCacheModel.Address = getAddress();

		String Address = bankCacheModel.Address;

		if ((Address != null) && (Address.length() == 0)) {
			bankCacheModel.Address = null;
		}

		return bankCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Bank, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Bank, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Bank, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Bank)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Bank, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Bank, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Bank, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Bank)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Bank>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _Bank_id;
	private String _BankName;
	private long _Bic;
	private String _Address;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Bank, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Bank)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("Bank_id", _Bank_id);
		_columnOriginalValues.put("BankName", _BankName);
		_columnOriginalValues.put("Bic", _Bic);
		_columnOriginalValues.put("Address", _Address);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("Bank_id", 2L);

		columnBitmasks.put("BankName", 4L);

		columnBitmasks.put("Bic", 8L);

		columnBitmasks.put("Address", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Bank _escapedModel;

}