/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package DataBase.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;My_Employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>DataBase.model.impl.EmployeeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>DataBase.model.impl.EmployeeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Employee
 * @generated
 */
@ProviderType
public interface EmployeeModel extends BaseModel<Employee> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee model instance should use the {@link Employee} interface instead.
	 */

	/**
	 * Returns the primary key of this employee.
	 *
	 * @return the primary key of this employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee.
	 *
	 * @param primaryKey the primary key of this employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this employee.
	 *
	 * @return the uuid of this employee
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this employee.
	 *
	 * @param uuid the uuid of this employee
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the prson_id of this employee.
	 *
	 * @return the prson_id of this employee
	 */
	public long getPrson_id();

	/**
	 * Sets the prson_id of this employee.
	 *
	 * @param Prson_id the prson_id of this employee
	 */
	public void setPrson_id(long Prson_id);

	/**
	 * Returns the last name of this employee.
	 *
	 * @return the last name of this employee
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this employee.
	 *
	 * @param LastName the last name of this employee
	 */
	public void setLastName(String LastName);

	/**
	 * Returns the first name of this employee.
	 *
	 * @return the first name of this employee
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this employee.
	 *
	 * @param FirstName the first name of this employee
	 */
	public void setFirstName(String FirstName);

	/**
	 * Returns the patronymic of this employee.
	 *
	 * @return the patronymic of this employee
	 */
	@AutoEscape
	public String getPatronymic();

	/**
	 * Sets the patronymic of this employee.
	 *
	 * @param Patronymic the patronymic of this employee
	 */
	public void setPatronymic(String Patronymic);

	/**
	 * Returns the date_of_birth of this employee.
	 *
	 * @return the date_of_birth of this employee
	 */
	public Date getDate_of_birth();

	/**
	 * Sets the date_of_birth of this employee.
	 *
	 * @param Date_of_birth the date_of_birth of this employee
	 */
	public void setDate_of_birth(Date Date_of_birth);

	/**
	 * Returns the date_of_start_work of this employee.
	 *
	 * @return the date_of_start_work of this employee
	 */
	public Date getDate_of_start_work();

	/**
	 * Sets the date_of_start_work of this employee.
	 *
	 * @param Date_of_start_work the date_of_start_work of this employee
	 */
	public void setDate_of_start_work(Date Date_of_start_work);

	/**
	 * Returns the work number of this employee.
	 *
	 * @return the work number of this employee
	 */
	public long getWorkNumber();

	/**
	 * Sets the work number of this employee.
	 *
	 * @param WorkNumber the work number of this employee
	 */
	public void setWorkNumber(long WorkNumber);

	/**
	 * Returns the position_ ID of this employee.
	 *
	 * @return the position_ ID of this employee
	 */
	public long getPosition_Id();

	/**
	 * Sets the position_ ID of this employee.
	 *
	 * @param Position_Id the position_ ID of this employee
	 */
	public void setPosition_Id(long Position_Id);

	/**
	 * Returns the home number of this employee.
	 *
	 * @return the home number of this employee
	 */
	public long getHomeNumber();

	/**
	 * Sets the home number of this employee.
	 *
	 * @param HomeNumber the home number of this employee
	 */
	public void setHomeNumber(long HomeNumber);

	/**
	 * Returns the bank_id of this employee.
	 *
	 * @return the bank_id of this employee
	 */
	public long getBank_id();

	/**
	 * Sets the bank_id of this employee.
	 *
	 * @param Bank_id the bank_id of this employee
	 */
	public void setBank_id(long Bank_id);

	/**
	 * Returns the is archive of this employee.
	 *
	 * @return the is archive of this employee
	 */
	public long getIsArchive();

	/**
	 * Sets the is archive of this employee.
	 *
	 * @param IsArchive the is archive of this employee
	 */
	public void setIsArchive(long IsArchive);

}